; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
board_microros_transport = serial
board_microros_distro = jazzy
board_microros_user_meta = ./action.meta
monitor_speed = 115200
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    gin66/FastAccelStepper@^0.34.0
    ;janelia-arduino/TMC2209@^10.1.1

[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
lib_ldf_mode = chain+


; upload_protocol = picotool
upload_protocol = cmsis-dap
debug_tool = cmsis-dap

lib_extra_dirs = lib/motor 
board_microros_extra_packages = extra_packages

build_flags = -Wall -Wextra -I lib -I src/base_controller -D__FREERTOS=1 -D CORE_DEBUG_LEVEL=5 -D ARDUINO_USB_MODE=1 -D CFG_TUSB_MCU=OPT_MCU_RP2040

; [env:esp32c3]
; platform = espressif32
; board = seeed_xiao_esp32c3
; framework = arduino
